bubbleSort: bubbleSort.c
	gcc -o bubbleSort.exe bubbleSort.c
selectionSort: selectionSort.c
	gcc -o selectionSort.exe selectionSort.c
insertionSort: insertionSort.c
	gcc -o insertionSort.exe insertionSort.c
shellSort: shellSort.c
	gcc -o shellSort.exe shellSort.c
quickSort: quickSort.c
	gcc -o quickSort.exe quickSort.c
margeSort: margeSort.c
	gcc -o margeSort.exe margeSort.c
heapSort: heapSort.c
	gcc -o heapSort.exe heapSort.c
